### ISSUE TITLE
Support newer Thunderbirds (72+)

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/keepassxc-mail#17]
`ExtensionSupport.registerWindowListener` seems not to work in newer Thunderbirds and therefore all GUI hooks from the "experiment" do not work.

**Comment by kkapsner** [comment]
It works, but the chromeURLs are different and the strings changed...

**Comment by spodermenpls** [comment]
@kkapsner I've seen you are a fellow Thunderbird user and developer, I've started a little project to re-introduce the post-TB 78 ability for typographic quotes (which would probably useful for you as well, since you're a fellow German), by re-writing the old XUL add-on as a MailExtension: https://github.com/spodermenpls/smartquotes. I've gathered support of two fellow devs, but they are all short on time, and I'm short on skill. Maybe you'd like to join our little cabal, and lend a hand whenever you might have a free minute to spare?

**Comment by kkapsner** [comment]
I may be able to lend a hand and give the project some basic functionality.

> whenever you might have a free minute to spare

... big "whenever" there.

Do you want me to create a fork and perform merge requests or do you want me to be an author on your repo?

**Comment by spodermenpls** [comment]
@kkapsner I've added you as a collaborator. No worries about being short on time as well, there's no deadline on this one. 😄
