### ISSUE TITLE
Support Passwords for Private-Keys

### ISSUE THREAD

**Issue by BarbarossaCode** [kkapsner/keepassxc-mail#60]
It would be nice if the extension would provide the possibility to retrive the password of private OpenPGP keys.
Edit: Support for CalDav passwords would also be nice.

**Comment by kkapsner** [comment]
Sounds like a good idea and should be doable.

CalDav should already work. It works for me.

**Comment by BarbarossaCode** [comment]
For me the extention seemed to interrupt the setup process for a new email account. By standard Thunderbird searches at the end for CardDav adressbooks and CalDav calendars. For my adressbook the correct password was suggestet. But for my calendat no password was recomended at all, but username, server, etc. are all the same. I`d guess it might be a onetime error.

**Comment by kkapsner** [comment]
You can look at the console (Ctrl+Shift+J) and there you can see when keepassxc-mail requests a password. Maybe the protocol was wrong.

The OpenPGP thing is a little bit more complicated because it does not use string bundles.

@jobisoft: I did not find how to get the `Localization` constructor (to be used like [here](https://searchfox.org/comm-central/source/mail/extensions/openpgp/content/ui/keyWizard.js#1075)). In the Thunderbird code it seems to be available in the global namespace. But in the experiment it's not. I could also not find it in `Cc`.
Also using `stringBundleService.createBundle("chrome://messenger/openpgp/keyWizard.ftl");` does not work as the format is different. (Throws `NS_ERROR_UNEXPECTED` when I call `GetStringFromName`.)
So how can I get the translations from `messenger/openpgp/keyWizard.ftl`?

**Comment by kkapsner** [comment]
@jobisoft: can you help? Also fine if not - just want to know if I should wait for an answer from you.

**Comment by jobisoft** [comment]
I am not sure. Can you try

XPCOMUtils.defineLazyGlobalGetters(this, ["Localization ]);

or

Cu.importGlobalProperties(["Localization "]);

**Comment by kkapsner** [comment]
Thanks. The first one works. I have to confess that I'm not familiar with how the global properties in Gecko work.

@BarbarossaCode: Now I have to implement the actual logic. I would say the "URL" in KeePassXC should be "openpgp://{FINGERPRINT OF THE KEY}" and no login should be set. Or what do you think?

Please check if the attached zip adds the KeePassXC-mail things to the password prompt.
[keepassxc-mail-1.1.zip](https://github.com/kkapsner/keepassxc-mail/files/9049790/keepassxc-mail-1.1.zip)

**Comment by BarbarossaCode** [comment]
I`m sorry at the moment i don`t have a Setup to test it at the moment.
