### ISSUE TITLE
Gmail OAuth tokens are stored in Thunderbird native password manager, not in KeepassXC

### ISSUE THREAD

**Issue by nodiscc** [kkapsner/keepassxc-mail#78]
**Steps to reproduce:**
- Setup native messaging, install the extension
- Add a Gmail account to Thunderbird
- The Gmail OAuth login form is displayed in a pop-up window
- Enter the Gmail password in the form (and possibly 2FA code), allow Thunderbird to access the account, the pop-up closes
- The OAuth token is still stored in Thunderbird's internal password manager, and not in KeepassXC
- Storing normal IMAP/SMTP passwords in KeepassXC works correctly.

**Comment by jplejacq-quoininc-com** [comment]
Same here on both Linux and Windows. Details on platforms:
1. Debian Bullseye, Thunderbird 102.4.0, KeePassXC 2.6.2, keepassxc-mail 1.3
2. Windows 11, Thunderbird 102.4.1, KeePassXC 2.7.4, keepassxc-mail 1.3

**Comment by mdonz** [comment]
FWIW, I do have one Gmail account (between other email accounts) in my Thunderbird, using oauth. I do not have a password entry for that in Thunderbird's internal password storage.
I do have a KeepassXC password entry for that account with URL "oauth://accounts.google.com". I cannot remember exact steps at the time but I believe that I let the initial set up process create the password entry in Thunderbird, then created the KeepassXC    entry manually with URL as above and username and password copied from the Thunderbird password entry and then removed the password entry in Thunderbird. After a TB restart, oauth has been working since with the KeepassXC entry here.

**Comment by kkapsner** [comment]
Yes, at the moment the oauth entries for mails have to be entered manually to the database.

I have some commented code that I have to check. It's something that is totally doable.

**Comment by jplejacq-quoininc-com** [comment]
Thanks for this information.

1. When you add the oath secret manually, what group does it have to go under? I don't see a group for KeePassXC-Mail which is what I expected.
2. I recommend updating the README warning about this. I spent a lot of time struggling with this. If you agree, I'd be happy to submit a pull request.

**Comment by kkapsner** [comment]
Please test 
[keepassxc-mail-1.3.1.zip](https://github.com/kkapsner/keepassxc-mail/files/9984888/keepassxc-mail-1.3.1.zip)

**Comment by kkapsner** [comment]
There is a conceptual problem when the token is renewed...

**Comment by StayPirate** [comment]
> There is a conceptual problem when the token is renewed...

Could you elaborate more on this point?

**Comment by kkapsner** [comment]
On renewal the implementation expects it to be changed immediately but we have to store it into the DB first. I have some ideas which seem to work OK. But further testing is required.

**Comment by StayPirate** [comment]
Hi, is there any update here?

**Comment by kkapsner** [comment]
Yes - you can start testing:
[keepassxc-mail-1.3.1.zip](https://github.com/kkapsner/keepassxc-mail/files/10420163/keepassxc-mail-1.3.1.zip)

**Comment by kkapsner** [comment]
It works fine for me so I will release 1.4

**Comment by nodiscc** [comment]
Thanks, works perfectly.
