### ISSUE TITLE
New profile does not find KeepassXC

### ISSUE THREAD

**Issue by CueHD** [kkapsner/keepassxc-mail#81]
I copied my Thunderbird profile to a separate drive to save space on my main SSD. I then deleted the original profile and pointed a new profile to the copied directory. When restarting Thunderbird, it asks for my password but does not provide any interface to Keepass XC. Everything worked well prior to copying the profile. Is there something that I need to do to point my copied profile to KeepassXC?

Windows 7
Thunderbird 102.9.0
Keepassxc-mail 1.4
KeepassXC 2.7.4

**Comment by CueHD** [comment]
Nevermind. After manually inputting the passwords once, it seems to connect again.

**Comment by kkapsner** [comment]
Does it still work after a Thunderbird restart?
Thunderbird caches the passwords so it might still not work properly.

When the problem is still present please give me screenshots of the error console (Ctrl + Shift + J) and the extension console (https://developer.thunderbird.net/add-ons/tips-and-tricks).

**Comment by CueHD** [comment]
Yes, it works after a reset. I am not sure why it didn't seem to work when I first started Thunderbird, but the problem has not returned.
