### ISSUE TITLE
Addon requests "Full unrestricted access to computer" permission

### ISSUE THREAD

**Issue by onitake** [kkapsner/keepassxc-mail#85]
## Description

When installing the KeepassXC-Mail into Thunderbird (from addons.thunderbird.net), it will ask the user for "Full unrestricted access to your computer".

## Expected Behaviour

The addon only requests permissions that are actually needed.

## Current Behaviour

Thunderbird will present a message box on installation, saying that full permissions to the local system are requested, with a link to https://support.mozilla.org/en-US/kb/permission-request-messages-thunderbird-extensions#w_have-full-unrestricted-access-to-thunderbird-and-your-computer

On the other hand, the [addon page](https://addons.thunderbird.net/en-GB/thunderbird/addon/keepassxc-mail/) shows the following:
```
    Access your data for https://api.github.com/
    Exchange messages with programs other than Firefox
```

## Possible Solution

I don't know if reducing the requested permissions is currently possible, but if it is possible, a refined permission set should be chosen.

It's also not clear why there is a difference between what's shown in Thunderbird and on addons.thunderbird.net.

## Steps to Reproduce (for bugs)

See above.

## Context

Broad local machine permissions open up a large attack surface and should be avoided.
It's always advisable to follow the [least privilege principle](https://en.wikipedia.org/wiki/Principle_of_least_privilege).

## Your Environment

* KeePassXC-mail version used: 1.5
* KeePassXC version: 2.7.4
* Thunderbird version: 102.11
* Operating system and version: Debian bookworm

**Comment by kkapsner** [comment]
I would like to reduce the permissions as far as possible. But it's not possible at the moment because Thunderbird has to API I can use to provide the passwords. Therefore I have to use a so called "experiment" which is executed in the very core of Thunderbird and therefore has the exact same rights as Thunderbird code.

So these are least privileges I need for it to work until the required API is present (https://bugzilla.mozilla.org/show_bug.cgi?id=1611700)

I do not know why there is a difference to the description on addons.thunderbird.net
